### ISSUE TITLE
Guac Spooler : unable to open database file

### ISSUE THREAD

**Issue by xpillons** [Azure/az-hop#1288]
```
2023-01-13 06:06:41,886 ERROR: unable to open database file
Traceback (most recent call last):
  File "/opt/cycle/guac/venv/lib/python3.6/site-packages/guac/daemon.py", line 67, in main
    autoscale_guac(config, ctx_handler=ctx_handler)
  File "/opt/cycle/guac/venv/lib/python3.6/site-packages/guac/autoscaler.py", line 85, in autoscale_guac
    demand_calculator.update_history()
  File "/opt/cycle/guac/venv/lib/python3.6/site-packages/hpc/autoscale/hpclogging.py", line 199, in apitrace_wrapper
    ret_val = function(*args, **kwargs)
  File "/opt/cycle/guac/venv/lib/python3.6/site-packages/hpc/autoscale/job/demandcalculator.py", line 193, in update_history
    self.node_history.update(list(self.__scheduler_nodes_queue) + failed_nodes)
  File "/opt/cycle/guac/venv/lib/python3.6/site-packages/hpc/autoscale/node/nodehistory.py", line 170, in update
    self._update(nodes)
  File "/opt/cycle/guac/venv/lib/python3.6/site-packages/hpc/autoscale/node/nodehistory.py", line 256, in _update
    self._execute(stmt)
  File "/opt/cycle/guac/venv/lib/python3.6/site-packages/hpc/autoscale/node/nodehistory.py", line 400, in _execute
    return self.conn.execute(stmt)
sqlite3.OperationalError: unable to open database file
2023-01-13 06:06:52,156 WARNING: Could not find private ip for 5kkna000000: [Errno -2] Name or service not known
2023-01-13 06:06:52,528 ERROR: Could not acquire lock (/opt/cycle/guac/scalelib.lock) - more than one instance is running.
```

**Comment by xpillons** [comment]
feature is deprecated
