### ISSUE TITLE
Cyclecloud autoscale "Failed to create node"

### ISSUE THREAD

**Issue by garvct** [Azure/az-hop#447]
When I get an interactive HB120rs_v2 with CycleCloud autoscaling

[garvct@ondemand ~]$ qsub -l select=1:ncpus=120:slot_type=hb120rs_v2 -I

I initially get the error below, but eventually I get a HB120rs_v2 in a running/ready state.?

"Autoscaling   Error: An unspecified error occurred"

Failed to create node
Virtual Machine
Get more help on this issue
Detail:
java.lang.NullPointerException
	at com.cyclecomputing.azure.ManagedDisks.assignLunsFromCell(ManagedDisks.java:518)
	at com.cyclecomputing.azure.autoscale.CellProcessor$CellController.setNodesCreating(CellProcessor.java:1251)
	at com.cyclecomputing.azure.autoscale.CellProcessor.process(CellProcessor.java:386)
	at com.cyclecomputing.azure.autoscale.CellProcessor.processCells(CellProcessor.java:126)
	at com.cyclecomputing.azure.autoscale.CellProcessor.processCells(CellProcessor.java:106)
	at sun.reflect.GeneratedMethodAccessor688.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:188)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:497)
	at org.python.core.PyObject.__call__(PyObject.java:501)
	at org.python.pycode._pyx432.handle$1(/opt/cycle_server/system/work/.plugins_expanded/.expanded/cloud-4b625c62-7d23-41b3-b6c6-9c64e7d3a3c4/plugins/azure/cluster/cell/update_scaleset.py:12)
	at org.python.pycode._pyx432.call_function(/opt/cycle_server/system/work/.plugins_expanded/.expanded/cloud-4b625c62-7d23-41b3-b6c6-9c64e7d3a3c4/plugins/azure/cluster/cell/update_scaleset.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:171)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:308)
	at org.python.core.PyFunction.function___call__(PyFunction.java:471)
	at org.python.core.PyFunction.__call__(PyFunction.java:466)
	at org.python.core.PyFunction.__call__(PyFunction.java:456)
	at org.python.core.PyFunction.__call__(PyFunction.java:451)
	at com.cyclecomputing.apex.plugin.python.BasePyPluginFunction.evaluate(BasePyPluginFunction.java:139)
	at com.cyclecomputing.apex.plugin.python.BasePyPluginFunction.call(BasePyPluginFunction.java:92)
	at com.cyclecomputing.apex.plugin.java.PluginInvocationHandler.invoke(PluginInvocationHandler.java:114)
	at com.sun.proxy.$Proxy58.handle(Unknown Source)
	at com.cyclecomputing.cloud.orchestration.OrchestrationPlugin._execute(OrchestrationPlugin.java:900)
	at com.cyclecomputing.cloud.orchestration.OrchestrationPlugin.executePhase(OrchestrationPlugin.java:722)
	at sun.reflect.GeneratedMethodAccessor669.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cyclecomputing.apex.plugin.java.JavaPluginFunction.call(JavaPluginFunction.java:157)
	at com.cyclecomputing.appsupport.task.impl.TaskOrganizer.run(TaskOrganizer.java:373)
	at com.cyclecomputing.appsupport.task.impl.TaskOrganizer.lambda$executeTaskBlocking$0(TaskOrganizer.java:78)
	at com.cyclecomputing.appsupport.task.impl.TaskOrganizer.runTask(TaskOrganizer.java:202)
	at com.cyclecomputing.appsupport.task.impl.TaskOrganizer.executeTaskBlocking(TaskOrganizer.java:78)
	at com.cyclecomputing.appsupport.task.impl.TaskCoordinator$TaskRunner.run(TaskCoordinator.java:356)
	at com.cyclecomputing.apex.plugin.impl.PluginTaskAdapter$PythonRunnable.run(PluginTaskAdapter.java:37)
	at com.cyclecomputing.apex.ad.auth.impl.ThreadContextTaskAdapter$CustomRunnable.run(ThreadContextTaskAdapter.java:42)
	at com.cyclecomputing.apex.event.impl.EventLogRunnable.run(EventLogRunnable.java:23)
	at com.cyclecomputing.core.concurrency.logging.LoggingRunnable.run(LoggingRunnable.java:31)
	at com.cyclecomputing.core.concurrency.BracketedQueueService$TaskRunner.run(BracketedQueueService.java:118)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by xpillons** [comment]
Should be fixed in CycleCloud 8.2.0
