### ISSUE TITLE
Error when starting SLURM nodes

### ISSUE THREAD

**Issue by xpillons** [Azure/az-hop#664]
```
Error fetching project slurm 2.5.0 from https://github.com/Azure/cyclecloud-slurm/releases/2.5.0: Unable to download asset: HTTP Error 503: Egress is over the account limit.
Storage Account
Get more help on this issue
Detail:
Traceback (most recent call last):
  File "/opt/cycle_server/system/work/.plugins_expanded/.expanded/cloud-2516dfb4-5d0f-45a9-b910-34da0cc81af7/plugins/cloud/cluster/phases/stage_resources.py", line 210, in handle
    _fetch_project(project, cache)
  File "/opt/cycle_server/system/work/.plugins_expanded/.expanded/cloud-2516dfb4-5d0f-45a9-b910-34da0cc81af7/plugins/cloud/cluster/phases/stage_resources.py", line 323, in _fetch_project
    raise Exception(msg)
Exception: Error fetching project slurm 2.5.0 from https://github.com/Azure/cyclecloud-slurm/releases/2.5.0: Unable to download asset: HTTP Error 503: Egress is over the account limit.

```

**Comment by xpillons** [comment]
this is a transient error being resolved after an autoscaling cycle.
