### ISSUE TITLE
Unable to connect to a Linux remote session : Authentication failed. Too many tries

### ISSUE THREAD

**Issue by xpillons** [Azure/az-hop#865]
Unable to connect to a Linux remote session : Authentication failed. Too many tries

**Comment by xpillons** [comment]
This is happening on the 4th shared session on the largeviz3d instance
```
#qstat -an1 | grep -i largeviz
53728.scheduler user1 vizq     sys-dashbo  14385   1   4    --    --  R 211:5 largeviz3d-1/0*4
56550.scheduler user2 vizq     sys-dashbo  46915   1   6    --    --  R 210:5 largeviz3d-1/1*6
67339.scheduler user3 vizq     sys-dashbo  11448   1   4    --  24:00 R 17:49 largeviz3d-1/3*4
68494.scheduler user4 vizq     sys-dashbo  39458   1   6    --    --  R 00:04 largeviz3d-1/2*6
```

**Comment by xpillons** [comment]
Setting VNC password...
Starting VNC server...

Warning: largeviz3d-1:2 is taken because of /tmp/.X2-lock
Remove this file if there is no X server largeviz3d-1:2

Desktop 'TurboVNC: largeviz3d-1:3 (john.doe)' started on display largeviz3d-1:3

Log file is vnc.log
Successfully started VNC server on largeviz3d-1:5903...
Script starting...
Starting websocket server...
The system default contains no modules
  (env var: LMOD_SYSTEM_DEFAULT_MODULES is empty)
  No changes in loaded modules

Launching desktop 'xfce'...
WebSocket server settings:
  - Listen on :61006
  - Flash security policy server
  - No SSL/TLS support (no cert file)
  - Backgrounding (daemon)
WARNING: no 'numpy' module, HyBi protocol will be slower
Traceback (most recent call last):
  File "/usr/bin/websockify", line 11, in <module>
    load_entry_point('websockify==0.8.0', 'console_scripts', 'websockify')()
  File "/usr/lib/python2.7/site-packages/websockify/websocketproxy.py", line 525, in websockify_init
    server.start_server()
  File "/usr/lib/python2.7/site-packages/websockify/websocket.py", line 973, in start_server
    tcp_keepintvl=self.tcp_keepintvl)
  File "/usr/lib/python2.7/site-packages/websockify/websocket.py", line 741, in socket
    sock.bind(addrs[0][4])
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
Scanning VNC log file for user authentications...
Generating connection YAML file...
generating cookie with syscall
generating cookie with syscall
generating cookie with syscall
generating cookie with syscall

(xfce4-session:24083): xfce4-session-WARNING **: 09:09:45.497: xfsm_manager_load_session: Something wrong with /anfhome/john.doe/.cache/sessions/xfce4-session-largeviz3d-1:3, Does it exist? Permissions issue?

ERROR: Unable to load info from any available system

xfwm4: Fatal IO error 4 (Interrupted system call) on X server :3.0.

(xfsettingsd:24103): libxfce4ui-WARNING **: 09:11:25.270: ICE I/O Error

(xfsettingsd:24103): libxfce4ui-WARNING **: 09:11:25.270: Disconnected from session manager.
xfsettingsd: Fatal IO error 11 (Resource temporarily unavailable) on X server :3.0.
xfce4-panel: Fatal IO error 4 (Interrupted system call) on X server :3.0.
xfdesktop: Fatal IO error 11 (Resource temporarily unavailable) on X server :3.0.

**Comment by xpillons** [comment]
https://discourse.openondemand.org/t/remote-desktop-new-connection-has-been-rejected-with-reason-authentication-failed/2749
