### ISSUE TITLE
Windows Remote Desktop not starting with user name containing a '.'

### ISSUE THREAD

**Issue by xpillons** [Azure/az-hop#957]
Guac spooler is failing to retrieve the user password from keyvault when the username contains a '.' (dot)

2022-07-19 08:45:10,659 ERROR: (BadParameter) The request URI contains an invalid name: john.john-password
Code: BadParameter
Message: The request URI contains an invalid name: praveen.routhu-password
Traceback (most recent call last):
  File "/opt/cycle/guac/venv/lib/python3.6/site-packages/guac/spooler.py", line 107, in get_user_password
    retrieved_secret = client.get_secret(f"{username}-password")
  File "/opt/cycle/guac/venv/lib/python3.6/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/opt/cycle/guac/venv/lib/python3.6/site-packages/azure/keyvault/secrets/_client.py", line 73, in get_secret
    **kwargs
  File "/opt/cycle/guac/venv/lib/python3.6/site-packages/azure/keyvault/secrets/_generated/_operations_mixin.py", line 1574, in get_secret
    return mixin_instance.get_secret(vault_base_url, secret_name, secret_version, **kwargs)
  File "/opt/cycle/guac/venv/lib/python3.6/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/opt/cycle/guac/venv/lib/python3.6/site-packages/azure/keyvault/secrets/_generated/v7_3/operations/_key_vault_client_operations.py", line 704, in get_secret
    raise HttpResponseError(response=response, model=error)
azure.core.exceptions.HttpResponseError: (BadParameter) The request URI contains an invalid name: john.john-password
Code: BadParameter
Message: The request URI contains an invalid name: john.john-password

**Comment by xpillons** [comment]
https://github.com/xpillons/azhop-guac/issues/10
